// <auto-generated />
namespace SMSApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatesmsappregistrationtablenewvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesmsappregistrationtablenewvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201807101054038_updatesmsappregistrationtablenewvalidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
